apiVersion: v2
name: sentry-relay
description: A Helm chart for the Sentry Relay
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.4
    condition: nginx.enabled
maintainers:
  - name: dossierdata
