{{- if .Values.relay.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}
  minReplicas: {{ .Values.relay.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.relay.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.relay.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
